#!/bin/bash
echo "this script is from github"
NUMBER=$(($NUMBERONE + $NUMBERTWO))
echo "$NUMBER"
echo "test message for pull command on jenkins"
echo "One more test message"
echo "this was run automatically"
echo "more echo"
echo "read:repo_hook add access" 
echo "restart jenkinsppu"
echo  " admin:repo_hook  Full control of repository hooks   write:repo_hook  Write repository hooks   read:repo_hook  Read repository hooks   admin:org_hook  Full control of organization hooks"
echo "Token 2"
echo "Update  tocken"
echo "Update  tocken"
echo "Update  tocken"
echo "Update  tocken2"
echo "Final test 1 "